version: '3'
services:
  # API
  api:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - './backend/:/var/www/html'
    command: bash -c "npm install && npm run start:debug"
    ports:
      - 3000:3000
      - 9229:9229
    restart: unless-stopped
    networks:
      - app

  # FRONTEND
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: node:16-alpine
    working_dir: /var/www/html
    command:  bash -c "npm install && npm run serve"
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - './frontend/:/var/www/html'
    networks:
      - app


# NETWORKS
networks:
  app:
    driver: bridge

